/* eslint-disable react/jsx-no-duplicate-props */
import { Montserrat } from "next/font/google";
import "./globals.css";

//components
import Navbar from "./components/Navbar"


const monster = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
      <body className={monster.className} >
     <Navbar/>
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"> 
        {children}
        </div>
        </body>
    </html>
  );
}
